### ISSUE TITLE
SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by khusamov** [fnogatz/xsd2json#67]
Operating System = Windows 10
Node 6.10

```javascript
var path = require('path');
var xsd2json = require('xsd2json');

var filename = path.join(__dirname, 'node_modules/xsd2json/test/XMLSchema2.xsd');

// use as function
xsd2json(filename, function(err, schemaObject) {
	if (err) console.log(err);
	console.log(JSON.stringify(schemaObject, null, 2));
});
```

```
[1] SyntaxError: Unexpected end of JSON input
[1]     at Object.parse (native)
[1]     at C:\@repositories\pir-model-preparer\node_modules\xsd2json\index.js:55:25
[1]     at ConcatStream.<anonymous> (C:\@repositories\pir-model-preparer\node_modules\concat-stream\index.js:36:43)
[1]     at emitNone (events.js:91:20)
[1]     at ConcatStream.emit (events.js:185:7)
[1]     at finishMaybe (C:\@repositories\pir-model-preparer\node_modules\readable-stream\lib\_stream_writable.js:504:14)
[1]     at endWritable (C:\@repositories\pir-model-preparer\node_modules\readable-stream\lib\_stream_writable.js:514:3)
[1]     at ConcatStream.Writable.end (C:\@repositories\pir-model-preparer\node_modules\readable-stream\lib\_stream_writable.js:484:41)
[1]     at Socket.onend (_stream_readable.js:511:10)
[1]     at Socket.g (events.js:291:16)
```

**Comment by fnogatz** [comment]
The XSD files directly located in the `/test` directory are just legacy and of no actual functionality or used in tests. I removed them now in version 1.11.4. Instead, you can check if the xsd2json module is working calling `npm test` or use some XSD file located in the `/test/xsd` directory, e.g. `/test/xsd/all_element.xsd`.
