### ISSUE TITLE
Error when attempting to use xsd2json

### ISSUE THREAD

**Issue by robgwheeler** [fnogatz/xsd2json#83]
Attempting to convert 5 XSDs linked by import using this tool and unfortunately it gets so far then stops with the following error: (I have installed swipl)

debug: Spawn prolog xsd2json program
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: spawn swipl ENOENT
    at _errnoException (util.js:1019:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:192:19)
    at onErrorNT (internal/child_process.js:374:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

unfortunately, i'm unable to provide the XSDs. Is there any other information I can provide to assist?

**Comment by fnogatz** [comment]
I have just uploaded version `1.11.6` of xsd2json which provides a `--debug-info` flag. Could you please reinstall this new version, run `xsd2json --debug-info` and copy its output here?

Do you install xsd2json globally or locally?

**Comment by fnogatz** [comment]
*ping* Any new on this, @robgwheeler? :)

**Comment by maliozer** [comment]
when I tried to use xsd2json the error is like that: ERROR: SGML2PL(xmlns): 
C:\Users\Mehmet Ali\AppData\Roaming\npm\\node_modules\xsd2json\lib-pl\cli.exe:7: Bad UTF-8 sequence

why 2 slashes between npm and node_modules ? 🤙 
how to fix utf-8 sequence ❓
